/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl_svr_primer_gui;

/**
 *
 * @author nando
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        ///colocar en el centro:
        this.setLocationRelativeTo(null);
        ///lo hacemos visible
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        agregarCliente = new javax.swing.JMenuItem();
        buscarCliente = new javax.swing.JMenuItem();
        editarCliente = new javax.swing.JMenuItem();
        eliminarCliente = new javax.swing.JMenuItem();
        Salir_01 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Reptiles = new javax.swing.JMenuItem();
        Mamiferos = new javax.swing.JMenuItem();
        Aves = new javax.swing.JMenuItem();
        todosAnimales = new javax.swing.JMenuItem();
        Salir_02 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        Operaciones = new javax.swing.JMenuItem();
        Administracion = new javax.swing.JMenuItem();
        Direccion = new javax.swing.JMenuItem();
        todoPersonal = new javax.swing.JMenuItem();
        Salir_03 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        sobreNosotros = new javax.swing.JMenuItem();
        Contacto = new javax.swing.JMenuItem();
        Salir_04 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Safari 506");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zebras.jpg"))); // NOI18N

        jMenu1.setText("Ingreso de personas");

        agregarCliente.setText("Agregar cliente");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(agregarCliente);

        buscarCliente.setText("Buscar cliente");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(buscarCliente);

        editarCliente.setText("Editar cliente");
        editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(editarCliente);

        eliminarCliente.setText("Eliminar cliente");
        eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarCliente);

        Salir_01.setText("Salir");
        Salir_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_01ActionPerformed(evt);
            }
        });
        jMenu1.add(Salir_01);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Animales");

        Reptiles.setText("Reptiles");
        Reptiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReptilesActionPerformed(evt);
            }
        });
        jMenu2.add(Reptiles);

        Mamiferos.setText("Mamiferos");
        Mamiferos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MamiferosActionPerformed(evt);
            }
        });
        jMenu2.add(Mamiferos);

        Aves.setText("Aves");
        Aves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvesActionPerformed(evt);
            }
        });
        jMenu2.add(Aves);

        todosAnimales.setText("Todos");
        todosAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosAnimalesActionPerformed(evt);
            }
        });
        jMenu2.add(todosAnimales);

        Salir_02.setText("Salir");
        Salir_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_02ActionPerformed(evt);
            }
        });
        jMenu2.add(Salir_02);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Personal Operativo");

        Operaciones.setText("Operaciones");
        Operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacionesActionPerformed(evt);
            }
        });
        jMenu8.add(Operaciones);

        Administracion.setText("Administracion");
        Administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministracionActionPerformed(evt);
            }
        });
        jMenu8.add(Administracion);

        Direccion.setText("Direccion");
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        jMenu8.add(Direccion);

        todoPersonal.setText("Todos");
        todoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoPersonalActionPerformed(evt);
            }
        });
        jMenu8.add(todoPersonal);

        Salir_03.setText("Salir");
        Salir_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_03ActionPerformed(evt);
            }
        });
        jMenu8.add(Salir_03);

        jMenuBar1.add(jMenu8);

        jMenu7.setText("Acerca de Safari506");

        sobreNosotros.setText("Sobre nosotros");
        sobreNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreNosotrosActionPerformed(evt);
            }
        });
        jMenu7.add(sobreNosotros);

        Contacto.setText("Contacto");
        Contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactoActionPerformed(evt);
            }
        });
        jMenu7.add(Contacto);

        Salir_04.setText("Salir");
        Salir_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_04ActionPerformed(evt);
            }
        });
        jMenu7.add(Salir_04);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        // TODO add your handling code here:
        Clientes c=new Clientes();
        c.agregar();
       
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
        Clientes c=new Clientes();
        c.buscar();
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteActionPerformed
        // TODO add your handling code here:
        Clientes c=new Clientes();
        c.editar();
    }//GEN-LAST:event_editarClienteActionPerformed

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
        // TODO add your handling code here:
        Clientes c=new Clientes();
        c.eliminar();
    }//GEN-LAST:event_eliminarClienteActionPerformed

    private void Salir_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_01ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Salir_01ActionPerformed

    private void ReptilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReptilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReptilesActionPerformed

    private void MamiferosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MamiferosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MamiferosActionPerformed

    private void AvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvesActionPerformed

    private void todosAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosAnimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosAnimalesActionPerformed

    private void Salir_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir_02ActionPerformed

    private void OperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperacionesActionPerformed

    private void AdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministracionActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void todoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todoPersonalActionPerformed

    private void Salir_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir_03ActionPerformed

    private void sobreNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreNosotrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobreNosotrosActionPerformed

    private void ContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactoActionPerformed

    private void Salir_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir_04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Administracion;
    private javax.swing.JMenuItem Aves;
    private javax.swing.JMenuItem Contacto;
    private javax.swing.JMenuItem Direccion;
    private javax.swing.JMenuItem Mamiferos;
    private javax.swing.JMenuItem Operaciones;
    private javax.swing.JMenuItem Reptiles;
    private javax.swing.JMenuItem Salir_01;
    private javax.swing.JMenuItem Salir_02;
    private javax.swing.JMenuItem Salir_03;
    private javax.swing.JMenuItem Salir_04;
    private javax.swing.JMenuItem agregarCliente;
    private javax.swing.JMenuItem buscarCliente;
    private javax.swing.JMenuItem editarCliente;
    private javax.swing.JMenuItem eliminarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem sobreNosotros;
    private javax.swing.JMenuItem todoPersonal;
    private javax.swing.JMenuItem todosAnimales;
    // End of variables declaration//GEN-END:variables
}
